// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjMSU7x-INQCGBcDAxy-4xExk0_XIBNbo',
    appId: '1:339184280127:web:5511d58ce30a3d4ebfce8a',
    messagingSenderId: '339184280127',
    projectId: 'kipu-app-87fa3',
    authDomain: 'kipu-app-87fa3.firebaseapp.com',
    storageBucket: 'kipu-app-87fa3.firebasestorage.app',
    measurementId: 'G-87G61V48YZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Nns3p_af_zdeBViHN78xq5_Jw5ECg0s',
    appId: '1:339184280127:android:dc6fb2335d78d39ebfce8a',
    messagingSenderId: '339184280127',
    projectId: 'kipu-app-87fa3',
    storageBucket: 'kipu-app-87fa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfRqIhJxRF0y_yMucuQtjFnIjFUqsPMrQ',
    appId: '1:339184280127:ios:6b3576017185a7b1bfce8a',
    messagingSenderId: '339184280127',
    projectId: 'kipu-app-87fa3',
    storageBucket: 'kipu-app-87fa3.firebasestorage.app',
    iosBundleId: 'com.kipu.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfRqIhJxRF0y_yMucuQtjFnIjFUqsPMrQ',
    appId: '1:339184280127:ios:6b3576017185a7b1bfce8a',
    messagingSenderId: '339184280127',
    projectId: 'kipu-app-87fa3',
    storageBucket: 'kipu-app-87fa3.firebasestorage.app',
    iosBundleId: 'com.kipu.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjMSU7x-INQCGBcDAxy-4xExk0_XIBNbo',
    appId: '1:339184280127:web:197df22c65f6b7e3bfce8a',
    messagingSenderId: '339184280127',
    projectId: 'kipu-app-87fa3',
    authDomain: 'kipu-app-87fa3.firebaseapp.com',
    storageBucket: 'kipu-app-87fa3.firebasestorage.app',
    measurementId: 'G-CQ6D0DYNGC',
  );

}
